modLoader="javafml"
loaderVersion="[43,)"
license="ARR"

[[mods]]
modId="peyroscythe"
version="1.20.1-1.2.1"
#logoFile="logo.png" #optional
displayName="Peyro's Scythe"
authors="Rinko1231"
description='''
Add some spells, weapons, etc. from the light novel, Savior From the Abyss.
Thanks to some Free assets from ssugmi, VerArc Stash, Kyrises!
'''